user/models.py
from application import db
import time

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(80), nullable=False)
    last_name = db.Column(db.String(80), nullable=False)
    username = db.Column(db.String(80), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password = db.Column(db.String, nullable=False)
    created = db.Column(db.Integer, default=int(time.time()))

    def __init__(self, first_name, last_name, username, email, password):
        self.first_name = first_name
        self.last_name = last_name
        self.username = username
        self.email = email
        self.password = password

    def __repr__(self):
        return f'<User {self.username}>'

user/forms.py
from flask_wtf import FlaskForm
from wtforms import validators, StringField, PasswordField
from wtforms.fields.html5 import EmailField
from wtforms.validators import ValidationError

from user.models import User

class RegisterForm(FlaskForm):
    first_name = StringField('First Name', [validators.DataRequired()])
    last_name = StringField('Last Name', [validators.DataRequired()])
    email = EmailField('Email Address', [validators.DataRequired(),
                                        validators.Email()])
    username = StringField('Username', [validators.DataRequired(),
                                        validators.length(min=4, max=25)])
    password = PasswordField('New Password', [validators.DataRequired(),
                                             validators.EqualTo('confirm',
                                                message='Passwords must match'),
                                             validators.length(min=4, max=80)])
    confirm = PasswordField('Repeat Password')

    # custom validators implement once i get the db up
    def validate_username(form, field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('Username already exists')

    def validate_email(form, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('Email already in use')

class LoginForm(FlaskForm):
    username = StringField('Username', [validators.DataRequired()])
    password = PasswordField('Password', [validators.DataRequired()])

app.py
from flask import Flask, render_template, url_for, request, session, redirect
from flask_wtf import FlaskForm
from wtforms import validators, StringField, PasswordField
from wtforms.fields.html5 import EmailField
from wtforms.validators import ValidationError
import bcrypt
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.secret_key = 'secret'
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:////Users/pat/Desktop/flask_demo/data.db'
db = SQLAlchemy(app)

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(80), nullable=False)
    last_name = db.Column(db.String(80), nullable=False)
    username = db.Column(db.String(80), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password = db.Column(db.String, nullable=False)

    def __repr__(self):
        return f'<User {self.username}>'

class RegisterForm(FlaskForm):
    first_name = StringField('First Name', [validators.Required()])
    last_name = StringField('Last Name', [validators.Required()])
    email = EmailField('Email Address', [validators.DataRequired(),
                                        validators.Email()])
    username = StringField('Username', [validators.Required(),
                                        validators.length(min=4, max=25)])
    password = PasswordField('New Password', [validators.Required(),
                                             validators.EqualTo('confirm',
                                                message='Passwords must match'),
                                             validators.length(min=4, max=80)])
    confirm = PasswordField('Repeat Password')

    # custom validators implement once i get the db up
    def validate_username(form, field):
        print('Field data from username check is {}'.format(field.data))
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('Username already exists')

    def validate_email(form, field):
        print('Field data from email check is {}'.format(field.data))
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('Email already in use')

class LoginForm(FlaskForm):
    username = StringField('Username', [validators.Required()])
    password = PasswordField('Password', [validators.Required()])

@app.route('/')
def home():
    return render_template('home.html')

@app.route('/about')
def about():
    return render_template('about.html')

@app.route('/register', methods=('GET', 'POST'))
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.hashpw(form.password.data.encode('utf8'), bcrypt.gensalt())
        user = User(
                    first_name=form.first_name.data,
                    last_name=form.last_name.data,
                    email=form.email.data,
                    username=form.username.data,
                    password=hashed_password)
        db.session.add(user)
        db.session.commit()
        print(user.username, user.email, user.password)
        return 'User Registered'
    return render_template('register.html', form=form)

@app.route('/login', methods=('GET', 'POST'))
def login():
    form = LoginForm()
    error = None
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user:
            password_check = bcrypt.checkpw(form.password.data.encode('utf8'), user.password)
            if password_check:
                session['username'] = form.username.data
                return 'User Logged In'
            else:
                user = None #if password fails overwrite previous user
        if not user: # this structure necessary to avoid username guessing
            error = 'Invalid credentials'
    return render_template('login.html', form=form, error=error)

if __name__ == '__main__':
    app.run(debug=True)

user/views.py
from flask import Blueprint, render_template, request, redirect, session
import bcrypt

from user.forms import RegisterForm, LoginForm
from user.models import User
from application import db

user_app = Blueprint('user_app', __name__)

@user_app.route('/register', methods=('GET', 'POST'))
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.hashpw(form.password.data.encode('utf8'), bcrypt.gensalt())
        user = User(
                    first_name=form.first_name.data,
                    last_name=form.last_name.data,
                    email=form.email.data,
                    username=form.username.data,
                    password=hashed_password)
        db.session.add(user)
        db.session.commit()
        return 'User Registered'
    return render_template('user/register.html', form=form)

@user_app.route('/login', methods=('GET', 'POST'))
def login():
    form = LoginForm()
    error = None
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user:
            password_check = bcrypt.checkpw(form.password.data.encode('utf8'), user.password)
            if password_check:
                session['username'] = form.username.data
                return 'User Logged In'
            else:
                user = None #if password fails overwrite previous user
        if not user: # this structure necessary to avoid username guessing
            error = 'Invalid credentials'
    return render_template('user/login.html', form=form, error=error)

templates/_formhelpers.html
{% macro render_field(field) %}
<div class="form-group">
  {{ field.label }}
  {{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class="text-danger">
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
</div>
{% endmacro %}

templates/about.html
{% extends 'base.html' %}
{% block title %}About{% endblock %}
{% block content %}
    <div>
      <h1>I'm a python enthusiast and my specific interests include:</h1>
      <ul>
        <li>Web Dev including REST API Development</li>
        <li>Machine/Deep Learning</li>
        <li>Data Engineering/Science</li>
      </ul>
    </div>
    {% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">

    {% block header %}{% endblock %}

  </head>
  <body>
    <header>
        <h1>Pat's Web App</h1>
        <nav>
          <ul>
            <li><a href="{{ url_for('home') }}">Home</a></li>
            <li><a href="{{ url_for('about') }}">About Me</a></li>
            <li><a href="{{ url_for('user_app.register') }}">Register</a></li>
            <li><a href="{{ url_for('user_app.login') }}">Login</a></li>
          </ul>
        </nav>
    </header>

    <div class="container">

      {% block content %}{% endblock %}

      <div class="col-md-offset-3 col-md-6">
        <hr />
        <footer>
        </footer>
      </div>

    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery-1.12.1.min.js"></script>

    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    {% block end_body_js %}{% endblock %}

  </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% block content %}
    <div>
      <h1>A Python Product</h1>
      <p>Made with Python, Flask and SQLAlchemy.</p>
    </div>
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block content %}

<div class="row">

  <div class="col-md-offset-3 col-md-6">

    <h3>Login:</h3>

    {% if error %}
    <div class="error text-danger">{{ error }}</div>
    {% endif %}

    {% from "_formhelpers.html" import render_field %}
    <form method="POST" action="{{ url_for('login')}}" role="form">

      {{ form.hidden_tag() }}

      {{ render_field(form.username, class='form-control') }}

      {{ render_field(form.password, class='form-control') }}

      <button type="submit" class="btn btn-default">Login</button>

    </form>

  </div>

</div>
{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block title %}Registration{% endblock %}

{% block content %}

<div class="row">

  <div class="col-md-offset-3 col-md-6">

    <h3>Registration:</h3>

    {% from "_formhelpers.html" import render_field %}
    <form method="POST" action="{{ url_for('register')}}" role="form">

      {{ form.hidden_tag() }}

      {{ render_field(form.first_name, class='form-control') }}
      {{ render_field(form.last_name, class='form-control') }}

      {{ render_field(form.username, class='form-control', placeholder="Only letters, numbers, dash and underscore") }}
      {{ render_field(form.email, class='form-control') }}

      {{ render_field(form.password, class='form-control', placeholder="At least 4 characters") }}
      {{ render_field(form.confirm, class='form-control') }}

      <button type="submit" class="btn btn-default">Register</button>

    </form>

  </div>

</div>
{% endblock %}

templates/user/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block content %}

<div class="row">

  <div class="col-md-offset-3 col-md-6">

    <h3>Login:</h3>

    {% if error %}
    <div class="error text-danger">{{ error }}</div>
    {% endif %}

    {% from "_formhelpers.html" import render_field %}
    <form method="POST" action="{{ url_for('user_app.login')}}" role="form">

      {{ form.hidden_tag() }}

      {{ render_field(form.username, class='form-control') }}

      {{ render_field(form.password, class='form-control') }}

      <button type="submit" class="btn btn-default">Login</button>

    </form>

  </div>

</div>
{% endblock %}

templates/user/register.html
{% extends "base.html" %}

{% block title %}Registration{% endblock %}

{% block content %}

<div class="row">

  <div class="col-md-offset-3 col-md-6">

    <h3>Registration:</h3>

    {% from "_formhelpers.html" import render_field %}
    <form method="POST" action="{{ url_for('user_app.register')}}" role="form">

      {{ form.hidden_tag() }}

      {{ render_field(form.first_name, class='form-control') }}
      {{ render_field(form.last_name, class='form-control') }}

      {{ render_field(form.username, class='form-control', placeholder="Only letters, numbers, dash and underscore") }}
      {{ render_field(form.email, class='form-control') }}

      {{ render_field(form.password, class='form-control', placeholder="At least 4 characters") }}
      {{ render_field(form.confirm, class='form-control') }}

      <button type="submit" class="btn btn-default">Register</button>

    </form>

  </div>

</div>
{% endblock %}